---
- name: Set up the initial swarm manager
  hosts: swarmManagers[0]
  become: true
  vars_files:
    - vars.yml

  tasks:
    - name: Start visualization container
      command: docker run -it -d -p 8080:8080 -e HOST={{ ansible_nodename }} -v /var/run/docker.sock:/var/run/docker.sock alexellis2/visualizer-arm

    - name: Initialize the swarm
      command: docker swarm init

    - name: Retrieve worker token from swarm manager
      command: docker swarm join-token -q worker
      register: workerToken
    - debug: msg="Worker Token={{ workerToken.stdout }}"

    - name: Retrieve manager token from swarm manager
      command: docker swarm join-token -q manager
      register: managerToken
    - debug: msg="Manager Token={{ managerToken.stdout }}"

    - name: Turn the red led off
      shell: "{{ red.ledOff }}"

    - name: Turn the blue led on
      shell: "{{ blue.ledOn }}"

- name: Open Safari browser with a specific URL
  hosts: 127.0.0.1

  tasks:
    - command: "open http://{{ hostvars[groups['swarmManagers'][0]]['ansible_nodename'] }}:8080"

- name: Add the worker nodes to the swarm
  hosts: swarmNodes
  become: true
  vars_files:
    - vars.yml

  tasks:
    - name: Join the worker node to the swarm
      command: docker swarm join --token {{ hostvars[groups['swarmManagers'][0]]['workerToken']['stdout'] }} {{ hostvars[groups['swarmManagers'][0]]['ansible_eth0']['ipv4']['address'] }}:2377
      register: result
    - debug: msg="{{ result.stdout }}"

    - name: Turn the red led off
      shell: "{{ red.ledOff }}"

    - name: Turn the green led on
      shell: "{{ green.ledOn }}"

- name: Add the manager nodes to the swarm
  hosts: additionalSwarmManagers
  become: true
  vars_files:
    - vars.yml

  tasks:
    - name: Join the manager node to the swarm
      command: docker swarm join --token {{ hostvars[groups['swarmManagers'][0]]['managerToken']['stdout'] }} {{ hostvars[groups['swarmManagers'][0]]['ansible_eth0']['ipv4']['address'] }}:2377
      register: result
    - debug: msg="{{ result.stdout }}"

    - name: Turn the red led off
      shell: "{{ red.ledOff }}"

    - name: Turn the blue led on
      shell: "{{ blue.ledOn }}"
